### ISSUE TITLE
compliment

### ISSUE THREAD

**Issue by faddat** [flisboac/docker-armhf-rethinkdb#1]
I love the way you hacked that into working.... Thanks!

**Comment by flisboac** [comment]
@faddat Well actually that was a failed attempt to make it work on my CuBox and an old version of Docker... It seems there's always a new sort of issue with Docker on ARM that prevents me from using any kind of software expected to run on x86 machines. And also, I ended up using another solution, so I won't really commit or continue working on this anymore.

And that raises the question, why haven't I deleted this repository yet? :)

**Comment by faddat** [comment]
heh.  Yeah I discovered that later, and used that, and don't even remember the repo's name.  I suppose you could delete the repo, but then how would people learn of a failed method?  Also, by mounting the cgroups from the host to the docker container, your method could be made to work-- that's what's up with SystemD in Docker.

**Comment by flisboac** [comment]
It has been almost 8 months since my last commit on the release branch. Since then a lot of things happened and I ended up focusing on running Docker on other non-ARM envorinments. Based on my local repositories, it seems I don't really have anything to commit, so what's in the releases branch is all I have... And that is basically using ArchlinuxARM with their build of RethinkDB for use as substitution for the database container of [Shipyard](https://shipyard-project.com/) (I guess). So, while I'm not really deleting the repository, there's nothing more for me to contribute.

Nice tip, though... I was not aware of the cgroups issue, I may come back to Docker on ARM when I get the chance!
